# This file was generated by GoReleaser. DO NOT EDIT.
cask "garminctl-cli" do
  version "0.5.0"

  on_macos do
    on_intel do
      sha256 "89f0114a2e0479a6340e553c8281874dfdc1fa296a86e1556d555181a235c2c3"
      url "https://github.com/jjuanrivvera/garminctl/releases/download/v#{version}/garminctl_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "d3a7b8eed2ef64a57ddd22aecdf54581009fdd3c27dcbb66f224ec7f2684bbe7"
      url "https://github.com/jjuanrivvera/garminctl/releases/download/v#{version}/garminctl_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "ee0f02d5d64ab080b69ad69ee23090846bfdd7d70928333bb099ffe18f1c3ae3"
      url "https://github.com/jjuanrivvera/garminctl/releases/download/v#{version}/garminctl_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "c1e033f077b94687b5d92ececebc713512ff9ba7feace08b34bf33cf7d7ab06b"
      url "https://github.com/jjuanrivvera/garminctl/releases/download/v#{version}/garminctl_#{version}_linux_arm64.tar.gz"
    end
  end

  name "garminctl-cli"
  desc ""
  homepage "https://github.com/jjuanrivvera/garminctl"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "garminctl"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/garminctl"]
  end

  # No zap stanza required

end
