# This file was generated by GoReleaser. DO NOT EDIT.
cask "garminctl-cli" do
  version "0.5.2"

  on_macos do
    on_intel do
      sha256 "632dd9ebfe81ba3cb330bba624999b43797b69d7ba5cd370b67cb8adf8469286"
      url "https://github.com/jjuanrivvera/garminctl/releases/download/v#{version}/garminctl_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "a9d87c1e689587e10ebfc8fac5921139b01a77ef2721bb4aee86b696baced894"
      url "https://github.com/jjuanrivvera/garminctl/releases/download/v#{version}/garminctl_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "0d11382a3723f9756622ebac78c544c36a7d94e921ff3651d49593fc3400ecab"
      url "https://github.com/jjuanrivvera/garminctl/releases/download/v#{version}/garminctl_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "aed87c2ce578b1780ebc0f053bb7cccb232f3316e6e59164002922e58069559f"
      url "https://github.com/jjuanrivvera/garminctl/releases/download/v#{version}/garminctl_#{version}_linux_arm64.tar.gz"
    end
  end

  name "garminctl-cli"
  desc ""
  homepage "https://github.com/jjuanrivvera/garminctl"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "garminctl"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/garminctl"]
  end

  # No zap stanza required

end
