# This file was generated by GoReleaser. DO NOT EDIT.
cask "garminctl-cli" do
  version "0.2.0"

  on_macos do
    on_intel do
      sha256 "74e8c89b0a047122b4ed261d07331fddf45b31594833a96f99f5db4cd39973d1"
      url "https://github.com/jjuanrivvera/garminctl/releases/download/v#{version}/garminctl_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "1f70211c841e613c65c253eaa066378c676c0e18e4fd0173aa1f67f0becfcb80"
      url "https://github.com/jjuanrivvera/garminctl/releases/download/v#{version}/garminctl_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "57963757465fa2adb6acc8b132b736450c8555081336ff259a1a81b60b2ace8b"
      url "https://github.com/jjuanrivvera/garminctl/releases/download/v#{version}/garminctl_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "c24f17157caa2b349eff9afa76eabddf5d583b619d1bf236519964ee02570f10"
      url "https://github.com/jjuanrivvera/garminctl/releases/download/v#{version}/garminctl_#{version}_linux_arm64.tar.gz"
    end
  end

  name "garminctl-cli"
  desc ""
  homepage "https://github.com/jjuanrivvera/garminctl"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "garminctl"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/garminctl"]
  end

  # No zap stanza required

end
